---
- name : Check Ansible failure message
  hosts: Puppet
#  become: yes
#  become_method: sudo
  serial: 1
 # vars_files:
 #   - /password.yaml


  tasks:
  - name: this command prints FAILED when it fails
    command: /bin/false
    register: command_result
    ignore_errors: True

  - name: fail the play if the previous command did not succeed
    fail: msg="the previous command and tasks failed .."
    when: "command_result.rc != 0"
    #failed_when: command_result.rc != 0
